// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDK-hPFTSg81mvQJXjLTIF5FcAsn9PnPc',
    appId: '1:578548281562:web:090108fbbdfbf3494cb5e3',
    messagingSenderId: '578548281562',
    projectId: 'lcos-app-2e724',
    authDomain: 'lcos-app-2e724.firebaseapp.com',
    storageBucket: 'lcos-app-2e724.appspot.com',
    measurementId: 'G-D1ZFFZ41DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM7s9QmZRLE0YRfgXQkFkxPYI77mEAI4s',
    appId: '1:578548281562:android:fcc0b3ffc2775f2b4cb5e3',
    messagingSenderId: '578548281562',
    projectId: 'lcos-app-2e724',
    storageBucket: 'lcos-app-2e724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqsL4L6wxyPhAKAdmiwggMbpD36kBM1po',
    appId: '1:578548281562:ios:1a007f39693a0bc04cb5e3',
    messagingSenderId: '578548281562',
    projectId: 'lcos-app-2e724',
    storageBucket: 'lcos-app-2e724.appspot.com',
    iosClientId:
        '578548281562-mp0h88as93d33k1a0o5uev0n7kpgn8d8.apps.googleusercontent.com',
    iosBundleId: 'com.irfan.lcos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqsL4L6wxyPhAKAdmiwggMbpD36kBM1po',
    appId: '1:578548281562:ios:42aca5b3ff620fa24cb5e3',
    messagingSenderId: '578548281562',
    projectId: 'lcos-app-2e724',
    storageBucket: 'lcos-app-2e724.appspot.com',
    iosClientId:
        '578548281562-vo0b0o2mm8pjkp1i9943b2e096bef3hn.apps.googleusercontent.com',
    iosBundleId: 'com.irfan.lcos.RunnerTests',
  );
}
